# Code refactoring
It's code review time!

Please have a look at this awful code and make it better.

It's an eye-sore.

The following code is super bad (intentionally, I promise).
There's lots of identation errors, duplicated / copied+pasted code, improper use of methods, bad naming of variables etc.

Just a mess.

You can analyse the dataset using `pandas` - but the actual code will not use `pandas` but `csv`.

In [22]:
import pandas as pd
import csv


df = pd.read_csv('./resources/factory_salary.csv')

df.head(20)

,Date,Profession,Rank,Equipment,Insalubrity,Size_Production,Salary
0,2009-01-01,Metal heater,7,Heating furnaces,22,580,26020.0
1,2009-01-01,Metal heater,6,Heating furnaces,22,580,22980.0
2,2009-01-01,Metal heater,5,Heating furnaces,22,580,20350.0
3,2009-01-01,Metal heater,5,Heating furnaces,22,580,20350.0
4,2009-01-01,Metal heater,4,Heating furnaces,22,580,18090.0
5,2009-01-01,Metal planter,4,Heating furnaces,22,580,18090.0
6,2009-01-01,Refractory,4,Heating furnaces,11,580,16110.0
7,2009-01-01,Roller,7,Piercing mill,18,580,25300.0
8,2009-01-01,Roller,6,Piercing mill,18,580,22260.0
9,2009-01-01,Roller assistant,4,Piercing mill,18,580,17370.0
10,2009-01-01,Roller,7,Pilgrim mill,18,580,25300.0
11,2009-01-01,Roller,6,Pilgrim mill,18,580,22260.0
12,2009-01-01,Roller assistant,4,Pilgrim mill,18,580,17370.0
13,2009-01-01,Roller assistant,3,Pilgrim mill,18,580,15420.0
14,2009-01-01,Hot metal cutter,4,Pilgrim mill,16,580,17010.0
15,2009-01-01,Cleaner,3,Pilgrim mill,18,580,15420.0
16,2009-01-01,Roller,5,Sizing mill,18,580,19630.0
17,2009-01-01,Operator,5,Sizing mill,8,580,17830.0
18,2009-01-01,Operator,5,Sizing mill,8,580,17830.0
19,2009-01-01,Operator,4,Sizing mill,8,580,15570.0

In [23]:
def helper_result(index, column_name, options={}):
  result = []
  for row in csv_data:
    if row[index] == options[column_name]:
      result.append(row)

  return result



def finder(options = {}):
  with open("./resources/factory_salary.csv", "rt") as csvfile:
    data = csv.reader(csvfile, delimiter=',', quotechar='"')
      # skip header
    next(data)
    csv_data = []
    for row in data:
      csv_data.append(row)

  columns_names = ['Date', 'Profession', 'Rank', 'Equipment', 'Insalubrity',	'Size_Production',	'Salary']
  for column in columns_names:
    output = []
    if column in options:
      result = []
      for index, row in enumerate(csv_data):
        if row[index] == options[column]:
          result.append(row)
        mapped = {}
        mapped[column] = row[index]
        output.append(mapped)
      csv_data = result
      
    return output

#   if 'Profession' in options:
#     result = []
#     for row in csv_data:
#       if row[1] == options['Profession']:
#         result.append(row)
#     csv_data = result

#   if 'Equipment' in options:
#     result = []
#     for row in csv_data:
#       if row[3] == options['Equipment']:
#         result.append(row)
#     csv_data = result

#   if 'Size_Production' in options:
#     result = []
#     for row in csv_data:
#       if row[5] == options['Size_Production']:
#         result.append(row)
#     csv_data = result

#   if 'Date' in options:
#     result = []
#     for row in csv_data:
#       if row[0] == options['Date']:
#         result.append(row)
#     csv_data = result

#   output = []
#   for row in csv_data:
#     mapped = {}
#     mapped['Date'] = row[0]
#     mapped['Profession'] = row[1]
#     mapped['Rank'] = row[2]
#     mapped['Equipment'] = row[3]
#     mapped['Insalubrity'] = row[4]
#     mapped['Size_Production'] = row[5]
#     mapped['Salary'] = row[6]
#     output.append(mapped)

#   return output


# def finder_by(options):
#   with open("./resources/factory_salary.csv", "rt") as csvfile:
#     data = csv.reader(csvfile, delimiter=',', quotechar='"')
#     # skip header
#     next(data)
#     csv_data = []
#     for row in data:
#       csv_data.append(row)

#   if 'Profession' in options:
#     for row in csv_data:
#       if row[1] == options['Profession']:
#         mapped = {}
#         mapped['Date'] = row[0]
#         mapped['Profession'] = row[1]
#         mapped['Rank'] = row[2]
#         mapped['Equipment'] = row[3]
#         mapped['Insalubrity'] = row[4]
#         mapped['Size_Production'] = row[5]
#         mapped['Salary'] = row[6]
#         return mapped

#   if 'Equipment' in options:
#     for row in csv_data:
#       if row[3] == options['Equipment']:
#         mapped = {}
#         mapped['Date'] = row[0]
#         mapped['Profession'] = row[1]
#         mapped['Rank'] = row[2]
#         mapped['Equipment'] = row[3]
#         mapped['Insalubrity'] = row[4]
#         mapped['Size_Production'] = row[5]
#         mapped['Salary'] = row[6]
#         return mapped

#   if 'Rank' in options:
#     for row in csv_data:
#       if row[2] == options['Rank']:
#         mapped = {}
#         mapped['Date'] = row[0]
#         mapped['Profession'] = row[1]
#         mapped['Rank'] = row[2]
#         mapped['Equipment'] = row[3]
#         mapped['Insalubrity'] = row[4]
#         mapped['Size_Production'] = row[5]
#         mapped['Salary'] = row[6]
#         return mapped

#   if 'Date' in options:
#     for row in csv_data:
#       if row[0] == options['Date']:
#         mapped = {}
#         mapped['Date'] = row[0]
#         mapped['Profession'] = row[1]
#         mapped['Rank'] = row[2]
#         mapped['Equipment'] = row[3]
#         mapped['Insalubrity'] = row[4]
#         mapped['Size_Production'] = row[5]
#         mapped['Salary'] = row[6]
#         return mapped

#     raise RecordNotFound

# print(pd.DataFrame(finder(df['Rank'].head(10))))

# class RecordNotFound(Exception):
#   pass

           Date          Profession Rank                        Equipment  \
0    2009-01-01        Metal heater    7                 Heating furnaces
1    2009-01-01        Metal heater    6                 Heating furnaces
2    2009-01-01        Metal heater    5                 Heating furnaces
3    2009-01-01        Metal heater    5                 Heating furnaces
4    2009-01-01        Metal heater    4                 Heating furnaces
..          ...                 ...  ...                              ...
259  2009-08-01  Quality controller    7  Control and measuring equipment
260  2009-09-01  Quality controller    7  Control and measuring equipment
261  2009-10-01  Quality controller    7  Control and measuring equipment
262  2009-11-01  Quality controller    7  Control and measuring equipment
263  2009-12-01  Quality controller    7  Control and measuring equipment

    Insalubrity Size_Production              Salary
0            22             580             26020.0
1            22             580             22980.0
2            22             580             20350.0
3            22             580             20350.0
4            22             580             18090.0
..          ...             ...                 ...
259           0            1180  26342.235294117647
260           0            1080   25044.58823529412
261           0             780             22060.0
262           0            1020             24266.0
263           0             810             22060.0

[264 rows x 7 columns]

In [21]:
# test the code - this part is ok, don't worry - trust the QA Engineer

def test_finder_returns_events():
    assert len(finder({'Profession': 'Quality controller'})) == 12

def test_finder_returns_correct_keys():
    row = finder(
        {
            'Profession': 'Quality controller',
            'Date': '2009-11-01'
        }
    )
    keys = ['Date','Profession','Rank','Equipment','Insalubrity','Size_Production','Salary']
    values = ['2009-11-01','Quality controller','7','Control and measuring equipment','0','1020','24266.0']
    for i in range(0, len(keys)):
      assert row[0][keys[i]] == values[i]

def test_finder_returns_events_by_equipment():
    assert len(finder({'Equipment': 'Heating furnaces'})) == 84

def test_finder_returns_events_by_rank():
    assert len(finder({'Rank': '7'})) == 264

def test_finder_returns_no_events():
    assert len(finder({'Profession': 'Unemployed'})) == 0

def test_finder_by_event_by_equipment():
    row = finder_by({'Equipment': 'Heating furnaces'})
    keys = ['Date','Profession','Rank','Equipment','Insalubrity','Size_Production','Salary']
    values = ['2009-01-01','Metal heater','7','Heating furnaces','22','580','26020.0']
    for i in range(0, len(keys)):
      assert row[keys[i]] == values[i]

try:
    test_finder_returns_events()
    test_finder_returns_correct_keys()
    test_finder_returns_events_by_equipment()
    test_finder_returns_events_by_rank()
    test_finder_returns_no_events()
    test_finder_by_event_by_equipment()

    print('All tests passed!')
except Exception as e:
    print('FAILED')
    print(e.with_traceback)
    raise

All tests passed!